---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vcluster-namespace-default-role
  namespace: vcluster-namespace
rules:
  - apiGroups: ["apps"]
    resources: ["*"]
    verbs: ["*"]      
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]      
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vcluster-namespace-default-rb
  namespace: vcluster-namespace
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: vcluster-namespace-default-role
  apiGroup: rbac.authorization.k8s.io
