apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: jaeger
  namespace: default
spec:
  xaasRequestPipeline:
    # - abangser/playground-jaeger-request-pipeline:v0.1.0
    - ghcr.io/avillela/jaeger-request-pipeline:v0.1.0
  xaasCrd:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: jaegers.example.promise
    spec:
      group: example.promise
      names:
        kind: jaeger
        plural: jaegers
        singular: jaeger
      scope: Namespaced
      versions:
        - name: v1
          schema:
            openAPIV3Schema:
              properties:
                spec:
                  properties:
                    clusterSelectors:
                      default: { test: test }
                      x-kubernetes-preserve-unknown-fields: true
                      type: object
                  type: object
              type: object
          served: true
          storage: true

status: {}
