apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: oteloperator-ls
spec:
  workerClusterResources:
  xaasRequestPipeline:
  xaasCrd:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: oteloperators.example.promise
    spec:
      group: example.promise
      scope: Namespaced
      names:
        plural: oteloperators
        singular: oteloperator
        kind: oteloperator
      versions:
      - name: v1
        served: true
        storage: true
        schema:
          openAPIV3Schema:
            type: object
            properties:
              spec:
                type: object
                properties:
                  name:
                    type: string
